### ISSUE TITLE
investigate customcrafting+autocrafter integration error after implementation

### ISSUE THREAD

**Issue by LcorpOfficial** [LcorpOfficial/LCC-Minecraft-Server#47]
**Describe the bug**
```
[05:14:46 WARN]: [AutomatedCrafting] Task #9 for AutomatedCrafting v2.4 generated an exception
java.lang.NoSuchMethodError: 'me.wolfyscript.customcrafting.handlers.RecipeHandler me.wolfyscript.customcrafting.CustomCrafting.getRecipeHandler()'
at nl.dgoossens.autocraft.compat.CustomCraftingCompat.load(CustomCraftingCompat.java:25) ~[?:?]
at nl.dgoossens.autocraft.RecipeLoader.reload(RecipeLoader.java:97) ~[?:?]
at nl.dgoossens.autocraft.RecipeLoader.lambda$new$0(RecipeLoader.java:27) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Tuinity-"52f4d08"]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Tuinity-"52f4d08"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:949) ~[patched_1.16.4.jar:git-Tuinity-"52f4d08"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"52f4d08"]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
**To Reproduce**
1. Load the server
2. Panic

**Expected behavior**
automatedcrafting should hook into customcrafting correctly to recieve recipes
**Screenshots**

**Minecraft Info (please complete the following information):**
 Alphaship Config

**Additional context notes**
contact both devs

**Comment by LcorpOfficial** [comment]
use CC 1.6.1.0 and test. https://github.com/Aeltumn/automated_crafting/issues/23#issuecomment-873573401

**Comment by Nine-JuanJuan** [comment]
For follow up, cross integration between plugins not possible currently. Will investigate further in several months.
